version: "3.2"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/challenge"
      SPRING_DATASOURCE_USERNAME: "arch"
      SPRING_DATASOURCE_PASSWORD: "challenge"
      SPRING_PORT: "8080"
      MERCADO_TOKEN: "QmVhcmVyIFRFU1QtODk4NDk1ODM4NTM4MjU0OS0wMTA3MjAtOGI0NWU2ODBjZDA4NWY5OTc2ODYzYTk1NjU1ZGFmZjctMTQzNzE2NDc3"
      TOKEN_FALLBACK: "ODk4NDk1ODM4NTM4MjU0OS0wMTA3MjAtOGI0NWU2ODBjZDA4NWY5OTc2ODYzYTk1NjU1ZGFmZjctMTQzNzE2NDc3"
      MERCADO_API: "https://api.mercadopago.com"

    networks:
      - netChallenge
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: "arch"
      POSTGRES_PASSWORD: "challenge"
    ports:
      - "5432:5432"
    volumes:
      - volume-db-challenge:/var/lib/postgresql/data
    networks:
      - netChallenge
volumes:
  volume-db-challenge:
  valume-api-challenge:

networks:
  netChallenge:
    driver: bridge
